version: '3.8'

services:
  localstack:
    image: localstack/localstack:2.3
    container_name: localstack-python-dynamodb
    ports:
      - "4566:4566"
    environment:
      - SERVICES=dynamodb
      - DEBUG=1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - DATA_DIR=/tmp/localstack/data
      - LOCALSTACK_PERSISTENCE=1
      - LOCALSTACK_DISABLE_TMP_FOLDER_CLEAR=1
    volumes:
      - localstack_data:/tmp/localstack/data
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  localstack_data:
